### ISSUE TITLE
Remove palette, replace with direct colors buffer

### ISSUE THREAD

**Issue by dy** [dfcreative/regl-scatter2d#10]
Following discussion with @alexcjohnson and #1.

**Comment by alexcjohnson** [comment]
@dfcreative is this completed by the work you did for plotly/plotly.js#2377 ?

**Comment by dy** [comment]
@alexcjohnson not exactly. I just extended color palette here.
Actually it takes removing the palette completely, since color ids in palette `uint32` are now of the size of the color itself, so palette is useless.

**Comment by dy** [comment]
Fixed in #11
