### ISSUE TITLE
Fix for IE11 - don't use destructuring assign

### ISSUE THREAD

**Issue by jeffsenn** [dfcreative/regl-scatter2d#12]
Doesn't work in IE11 due to this line in scatter.js:

`const {float32, fract32} = require('to-float32')`

Fix (remove destructing assignment):

`const to_float32 = require('to-float32')`

`const float32 = to_float32.float32`

`const fract32 = to_float32.fract32`

**Comment by s-lee-kwong** [comment]
I am also having this issue, can this not be implemented?

**Comment by dy** [comment]
Should be fixed with 3.0.6
