### ISSUE TITLE
Polish API of viewport, scissor, translate and scale

### ISSUE THREAD

**Issue by dy** [dfcreative/regl-scatter2d#2]
Probably sending them to `draw` is good practice

**Comment by rreusser** [comment]
Does it make sense to use `scissor` box in order to restrict the draw region? This seems like (*maybe*) a straightforward to multiplex axes into the same webgl context while properly clipping the draw region. Of course if the geometry is placed/culled manually, maybe this is not relevant.

**Comment by dy** [comment]
@rreusser working on that. I thought calling it a `viewport` property.

**Comment by rreusser** [comment]
Cool. Yeah, that's a good name. [`scissor`](https://github.com/regl-project/regl/blob/gh-pages/API.md#scissor) just refers to the regl/opengl property. (It also has [`viewport`](https://github.com/regl-project/regl/blob/gh-pages/API.md#viewport), though I'm not actually sure what that does. Doesn't make sense to me what it means to resize the viewport/framebuffer by calling a draw command.)

**Comment by dy** [comment]
`viewport` option enables drawing to a part of canvas
