### ISSUE TITLE
array-bounds should be in dependencies instead of devDependencies

### ISSUE THREAD

**Issue by wolfd** [dfcreative/regl-scatter2d#22]
The `array-bounds` package is currently in devDependencies:
https://github.com/gl-vis/regl-scatter2d/blob/477bf6e4fc8e922efa9f2578616a5b4625cf90a4/package.json#L49

But it is used in `bundle.js`:
https://github.com/gl-vis/regl-scatter2d/blob/477bf6e4fc8e922efa9f2578616a5b4625cf90a4/bundle.js#L63

This breaks the install when `NODE_ENV=production`

**Comment by dy** [comment]
Thanks
