### ISSUE TITLE
image-palette has no license

### ISSUE THREAD

**Issue by lb-kamilk** [dfcreative/regl-scatter2d#34]
package image-palette has no license in npm https://www.npmjs.com/package/image-palette
This causes issues when using tools like snyk https://snyk.io/advisor/npm-package/image-palette

I don't see the package being used anywhere. Is it being called implicitly? Can we remove it, if it's not needed?

**Comment by archmoj** [comment]
The package is used in test files here: https://github.com/gl-vis/regl-scatter2d/blob/5689530d7690c9a08262e8b274a68d8f094d2029/test/index.js#LL5C37-L5C37

**Comment by archmoj** [comment]
Thanks addressed by `v3.2.9`.
