### ISSUE TITLE
Regl-component interface

### ISSUE THREAD

**Issue by dy** [dfcreative/regl-scatter2d#6]
Within all `regl-` components there is shareable pattern of code.

* [x] takes list of options with aliases - covered by [pick-by-alias](https://github.com/dfcreative/pick-by-alias)
* [x] provides only actual passed options in update, handles only provided params
* handles default `viewport`, `range` params
* `translate` and `scale` as pixel alternative to `range`
* evals functional params
* expose state of rendering, passing that to evaluated option properties, and letting read params, like `draw.range` or `draw.viewport`
* cache calculated state properties for corresponding input values
* cache drawing function
* `destroy` method? or just `update(null)`? Or `update({destroy})`?
* batch options argument to update.

**Comment by dy** [comment]
Implemented in https://github.com/dfcreative/regl-line2d/commit/8cc53f3d1daba994ee82092b00a1f3c0bd5f8c90 by [obj-map-prop](https://github.com/dfcreative/obj-map-prop) and [pick-by-alias](https://github.com/dfcreative/pick-by-alias)

**Comment by dy** [comment]
Some additional changes after practical work w/scatter plot

* [x] class interface: allows for extension/inheritance, reusing methods, naturally provides internal properties (unlike defined on some returned function), provides static methods/props (caching included), provides generic interface for related components, allows for generic methods.
* [x] batch should be better off as `update(a, b, c)` rather than `update([a, b, c])` - for nested options complacency. That simplifies `draw(els, els, els)` vs `draw([els, els, els])`. It is not batch in fact, that is multiple passes. Doing `update(a)` after `update(a, b)` removes `b` pass, in that `update` fully redefines state. (see [immutability-helper](https://github.com/kolodny/immutability-helper) for inspiration)
  * [ ] adding new items: ``
  * [ ] removing `i`-th item: ``
  * [ ] updating (extending) `i`-th item: ``
* [ ] common regl-component interface for external regl-batch: a set of layers/areas with attached renderers. Methods/props: `update`, `draw`, `destroy`, `viewport`, `render`.
* [ ] shaders should be shared class-wise, ie. if we have multiple regl-scatter instances, only buffers/textures/resources get recreated, but shader keeps as static instance. That is doable through context binding.
* [ ] make sure after resizing screen it is not necessary to call `update` to recalc viewport.

**Comment by etpinard** [comment]
Thanks for writing this down. Very helpful.

**Comment by dy** [comment]
Full gl-component interface is implemented by [gl-waveform](https://ghub.io/gl-waveform).
Main changes:
- no batching. Use multiple instances instead - that reduces code/API complexity significantly.
- `render` method instead of `draw`, for compatibility with virtual-dom
- `viewport` → `clip`, `flip`
- caching shaders
- regl is implicit - users don't care if that is regl or any other, besides it can be replaced with gl-util one day.
